config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => {:registrations => "users/registrations"}
 
  devise_scope :user do
      get '/admin', to: 'users/sessions#new'
  end

  root 'welcome#index'
  
  resources :roles
  
  resources :programs
  resources :calendars

end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
	has_many :cdays
	accepts_nested_attributes_for :cdays, :reject_if => :all_blank, :allow_destroy => true
	
	
	
	
end

app/models/cday.rb
class Cday < ApplicationRecord
	belongs_to :calendar
	has_many :ctasks
end

app/models/ctask.rb
class Ctask < ApplicationRecord
	belongs_to :cday
end

app/models/pday.rb
class Pday < ApplicationRecord
	belongs_to :program
	has_many :ptasks
	accepts_nested_attributes_for :ptasks, :reject_if => :all_blank, :allow_destroy => true
end

app/models/program.rb
class Program < ApplicationRecord
	has_many :pdays
	accepts_nested_attributes_for :pdays, :reject_if => :all_blank, :allow_destroy => true

end

app/models/ptask.rb
class Ptask < ApplicationRecord
	belongs_to :pday
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  
  has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:registerable, :confirmable
 
  attr_accessor :login
  

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 before_action :configure_permitted_parameters, if: :devise_controller?

 
  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
   end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
	def new
		 @calendar = Calendar.new
		 @calendar.cdays.build
	end

	def index
		if params[:name].present?
			@calendars = Calendar.where(name: params[:name])
		else
			@calendars = Calendar.all
		end 
	end

	def create
		@calendars = Calendar.new(calendar_params)
		if @calendars.save
			redirect_to @calendars
		else
			render 'new'
		end
	end
	
	def show
		 @calendar = Calendar.find(params[:id])
		 @previous_calendar = Calendar.where('id < ?', params[:id]).last
         @next_calendar  = Calendar.where('id > ?', params[:id]).first
	end

	private

	def calendar_params
		 params.require(:calendar).permit(:name, cdays_attributes:[:days ])
		
	end
end

app/controllers/pdays_controller.rb
class PdaysController < ApplicationController
	def new
		 @pday = Pday.new
		 @pday.ptasks.build
	end

	def index
		if params[:days].present?
			@pday = Pday.where(name: params[:days])
		else
			@pday = Pday.all
		end 
	end

	def create
		@pdays = Pday.new(pday_params)
		if @pdays.save
			redirect_to @pdays
		else
			render 'new'
		end
	end
	
	def show
		 @pday = Pday.find(params[:id])
	end

	private

	def pday_params
		 params.require(:pday).permit(:days,ptasks_attributes: [:description])
		
	end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
	def new
		 @program = Program.new
		 @program.pdays.build
	end

	def index
		if params[:name].present?
			@programs = Program.where(name: params[:name])
		else
			@programs = Program.all
		end 
	end

	def create
		@programs = Program.new(program_params)
		if @programs.save
			redirect_to @programs
		else
			render 'new'
		end
	end
	
	def show
		 @program = Program.find(params[:id])
	end

	private

	def program_params
		 params.require(:program).permit(:name,pdays_attributes: [:days ])
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    if params[:first_name].present? && params[:last_name].present? && params[:email].present? 
      @users = User.where(first_name: params[:first_name], last_name: params[:last_name], email: params[:email])
    elsif params[:first_name].present? || params[:last_name].present? || params[:email].present?
      @users = User.where(first_name: params[:first_name]).or(User.where(last_name: params[:last_name])).or(User.where(email: params[:email]))
    else
      @users = User.all
    end
  end

  def new
  	@user= User.new

  end
  
  def create
    puts params[:user['last_name']]
    generated_password = Devise.friendly_token.first(8)
  	@user = User.new(user_params)
    @role = Role.find(params[:user][:roles])
  	if @user.save
      @user.add_role @role.name
      @user.update(password: generated_password)
      @user.send_reset_password_instructions
  		respond_to do |format|
				format.js
			end
    else
    	render 'new'
    end

  end

  private
  def user_params
  	params.require(:user).permit(:first_name, :last_name,:email,:password,:date_of_birth,:mobile,:gender,:role)

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pdays_helper.rb
module PdaysHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/program_helper.rb
module ProgramHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calendars/_form.html.erb
<div class="card-block">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= nested_form_for(@calendar, remote: true) do |day_form| %>
    
      <div class="form-group row" >
        <label for="fname" class="col-md-4 control-label">Name</label><div class="col-md-8">
        <%= day_form.text_field :name %>
        </div>
       </div>
       <%= day_form.fields_for :cdays do |cday| %>
       <div class="form-group row" >
       <label for="fname" class="col-md-4 control-label">Days</label><div class="col-md-8">
         <%= cday.text_field :days %>
           </div>
           </div>
          <%= cday.link_to_remove "Remove this task"%>
         <% end %>
        
         <%= day_form.link_to_add "Add a task", :cdays %>
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-8">
            <%= day_form.submit :Submit, class: 'btn btn-success' %>
            </div>
          </div>
        </div>
         
        <% end %>
      </div>
    </div>
  </div>

app/views/calendars/index.html.erb
<p id="notice"><%= notice %></p>





<table class="table" align ="center" >
  <thead>
    <tr>
      <th>Name</th>
      <th align="center">Actions</th>
      <th colspan = "1 "></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @calendars.each do |calendar| %>
      <tr>
        <td><%= calendar.name %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/calendars/new.html.erb
<h1 align="center">Create your Program</h1></br>
 
<%= render 'form' %>

app/views/calendars/show.html.erb
<%= link_to "-->",@previous_calendar,{ style: "text-align:right;"  } %>
<p align="center">
  <strong>Name:</strong>
  <%= @calendar.name %>
</p>

<%= link_to "<--",new_program_path,{ style: "margin-left:8px; text-align:left;"  } %>

app/views/programs/_form.html.erb
<div class="card-block">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= nested_form_for(@program) do |prog| %>
        <div class="form-group row" >
          <label for="fname" class="col-md-4 control-label">Name</label><div class="col-md-8">
          <%= prog.text_field :name %>
          </div>
        </div>
       <%= prog.fields_for :pdays do |pday| %>
        <div class="form-group row" >
          <label for="fname" class="col-md-4 control-label">Days</label><div  class="col-md-8">
          <%= pday.text_field :days %>
          
          </div>
        </div>
          
        <% end %>
          <%= prog.link_to_add "Add days", :pdays %>
          <%= prog.link_to_remove "Remove days"%>
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-8">
            <%= prog.submit :Submit, class: 'btn btn-success' %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>





<table class="table" align ="center" >
  <thead>
    <tr>
      <th>Name</th>
      <th align="center">Actions</th>
      <th colspan = "1 "></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.name %></td>
        <td><%= link_to 'start', new_calendar_path , class: 'btn btn-info' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/programs/new.html.erb
<h1 align="center">New Program</h1></br>
 
<%= render 'form' %>

app/views/programs/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @program.name %>
</p>