config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => {:registrations => "users/registrations"}
 
  devise_scope :user do
      get '/admin', to: 'users/sessions#new'
  end

  root 'welcome#index'
  
  resources :roles
  
  resources :programs
  resources :calendars

end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
	has_many :cdays
	accepts_nested_attributes_for :cdays, :reject_if => :all_blank, :allow_destroy => true
	
	
	
	
end

app/models/cday.rb
class Cday < ApplicationRecord
	belongs_to :calendar
	has_many :ctasks
end

app/models/ctask.rb
class Ctask < ApplicationRecord
	belongs_to :cday
end

app/models/pday.rb
class Pday < ApplicationRecord
	belongs_to :program
	has_many :ptasks
	accepts_nested_attributes_for :ptasks, :reject_if => :all_blank, :allow_destroy => true
end

app/models/program.rb
class Program < ApplicationRecord
	has_many :pdays
	accepts_nested_attributes_for :pdays, :reject_if => :all_blank, :allow_destroy => true

end

app/models/ptask.rb
class Ptask < ApplicationRecord
	belongs_to :pday
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  
  has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:registerable, :confirmable
 
  attr_accessor :login
  

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end

end

app/controllers/pdays_controller.rb
class PdaysController < ApplicationController
	def new
		 @pday = Pday.new
		 @pday.ptasks.build
	end

	def index
		if params[:days].present?
			@pday = Pday.where(name: params[:days])
		else
			@pday = Pday.all
		end 
	end

	def create
		@pdays = Pday.new(pday_params)
		if @pdays.save
			redirect_to @pdays
		else
			render 'new'
		end
	end
	
	def show
		 @pday = Pday.find(params[:id])
	end

	private

	def pday_params
		 params.require(:pday).permit(:days,ptasks_attributes: [:description])
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    if params[:first_name].present? && params[:last_name].present? && params[:email].present? 
      @users = User.where(first_name: params[:first_name], last_name: params[:last_name], email: params[:email])
    elsif params[:first_name].present? || params[:last_name].present? || params[:email].present?
      @users = User.where(first_name: params[:first_name]).or(User.where(last_name: params[:last_name])).or(User.where(email: params[:email]))
    else
      @users = User.all
    end
  end

  def new
  	@user= User.new

  end
  
  def create
    puts params[:user['last_name']]
    generated_password = Devise.friendly_token.first(8)
  	@user = User.new(user_params)
    @role = Role.find(params[:user][:roles])
  	if @user.save
      @user.add_role @role.name
      @user.update(password: generated_password)
      @user.send_reset_password_instructions
  		respond_to do |format|
				format.js
			end
    else
    	render 'new'
    end

  end

  private
  def user_params
  	params.require(:user).permit(:first_name, :last_name,:email,:password,:date_of_birth,:mobile,:gender,:role)

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pdays_helper.rb
module PdaysHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/program_helper.rb
module ProgramHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   <p >Devise App with Bootstrap Designing</p>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', "nested_form",'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <% if user_signed_in? and current_user.is_admin? -%>
        <nav class="navbar navbar-inverse">
         <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Devise Test</a>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li><a href = "<%= destroy_user_session_path %>" data-method="delete" > <span class="glyphicon glyphicon-off"></span> Logout</a></li>
          </ul>
          
         
          
        </div>
      </nav> 
    Logged in as <strong><%= current_user.email %></strong></br>
    <%= link_to "Add Programs",new_program_path %>
    <% elsif user_signed_in? and !current_user.is_admin? -%>
        <nav class="navbar navbar-inverse">
         <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Devise Test</a>
          </div>
          
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Change Password", edit_user_registration_path %></li>
            <li><a href = "<%= destroy_user_session_path %>" data-method="delete" > <span class="glyphicon glyphicon-off"></span> Logout</a></li>
          </ul>
        </div>
      </nav>
      <p> All Programs </p>
    <%= link_to "Click here to see all programs",programs_path %>
    <div class="container">
    <% else %>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          
          <ul class="nav navbar-nav navbar-right">
            <li><a href = "<%= new_user_registration_path %>"> <span class="glyphicon glyphicon-user"></span>Sign up </a></li>
            <li><a href = "<%= new_user_session_path %>" ><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          </ul>
        </div>
      </nav> 
    <% end %>
    
    
    
     
        <%= yield %>
        <%= render 'layouts/footer' %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </body>
      </html>